version: '3.8'

services:

   pgadmin:
     image: dpage/pgadmin4:7.8
     restart: always
     environment:
       PGADMIN_DEFAULT_EMAIL: evegork@gmail.com
       PGADMIN_DEFAULT_PASSWORD: root
     ports:
       - "14000:80"
   database:
     image: postgres:15
     restart : always
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: test_db
     ports:
       - "55555:5432"
